from app.detectors import (
    address,
    card,
    cardholder,
    dates,
    department_code,
    document_context,
    driver_license,
    email,
    fio,
    foreign_passport,
    inn,
    passport,
    phone,
    secrets,
)