poet_stop:
  - поэт
  - писатель
  - художник
  - композитор
  - классик
address_stop:
  - отделение
  - доп. офис
  - дополнительный офис
  - офис банка
  - филиал
  - банкомат
fio_non_name:
  - живет
  - здесь
  - работает
  - находится
  - обратился
  - пришел
  - сказал
  - имеет
  - получает
  - проживает
  - зарегистрирован